// Generated by Copilot

#ifndef SUMARRAY_DEVICE_CUH
#define SUMARRAY_DEVICE_CUH

#include <cuda_runtime.h>

extern "C" void sumMatrixOnGPU(float *A, float *B, float *C, const int nx,
                               const int ny, const dim3 grid, const dim3 block);

#endif  // SUMARRAY_DEVICE_CUH
