// Generated by Copilot

#ifndef SUMARRAY_DEVICE_CUH
#define SUMARRAY_DEVICE_CUH

#include <cuda_runtime.h>

extern "C" void mathKernel1(float *c, int N, const dim3 grid, const dim3 block);
extern "C" void mathKernel2(float *c, int N, const dim3 grid, const dim3 block);
extern "C" void mathKernel3(float *c, int N, const dim3 grid, const dim3 block);
extern "C" void mathKernel4(float *c, int N, const dim3 grid, const dim3 block);
extern "C" void warmingup(float *c, int N, const dim3 grid, const dim3 block);

#endif  // SUMARRAY_DEVICE_CUH
