// Generated by Copilot

#ifndef GRID_AND_BLOCK_DEVICE_CUH
#define GRID_AND_BLOCK_DEVICE_CUH

#include <cuda_runtime.h>

extern "C" void checkIndex(dim3 grid, dim3 block);

#endif  // GRID_AND_BLOCK_DEVICE_CUH
